url: https://y7kim.github.io
baseurl: ''

# Site settings
title: The Edwards Lab
email: erika_edwards@brown.edu
description: "Erika Edwards's laboratory in the Department of Ecology and Evolutionary Biology at Brown University."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Erika Edwards
  pic: e_s
  position: Principal Investigator
  description: My CV is available <a href="/reprints/edwardsCVaug2014.pdf">here</a>.
  social:
    - title: twitter
      url: https://twitter.com/erikaedw
    - title: google
      url: https://scholar.google.com/citations?user=mlC_ztAAAAAJ&hl=en&authuser=1
    - title: github
      url: https://github.com/erikajedwards
   
- name: Abby Moore
  pic: abby_s
  position: Postdoc
  description: phylogenomics; ecological adaptation; evolution of succulence and CAM in Anacampserotaceae. <a href="/reprints/Moore_cv.pdf">CV</a>

 
      
- name: David Chatelet
  pic: david_s
  position: Postdoc
  description: plant structure and function; evolution and functional consequences of diversity in leaf designs. <a href="reprints/CV_Sept2013_Chatelet.pdf">CV</a>
  social: 
    - title: google
      url: https://scholar.google.com/citations?user=Hy3Pfe4AAAAJ&hl=en&authuser=1
      
- name: Laura Garrison
  pic: laura_s
  position: Graduate Student
  description: plant systematics, desert floras, plant phenology and the effects of rapid environmental change on ecosystems. <a href="/reprints/LauraGarrisonCV.pdf">CV</a>
 
      
- name: Lilly Hancock
  pic: lilly_s
  position: Graduate Student
  description: evolution of CAM photosynthesis; Australian Montiaceae. <a href="reprints/HancockCVAug2012.pdf">CV</a>
  social:
   - title: twitter
     url: https://twitter.com/lillypine28
 
- name: Morgan Moeglein
  pic: Morgan1
  position: Graduate Student
  description: Genetic basis of ecologically relevant traits; leaf shape evolution in Viburnum. <a href="reprints/Moeglein_CV_2014.pdf">CV</a>
 
- name: Lucy
  pic: lucy_moss
  position: Research Assistant
  description: botanical illustration; mosses 
 
- name: Henry
  pic: henry1_s
  position: Research Assistant
  description: flora of Mt. Kinabalu; bananas 
 





# Postal address (add as many lines as necessary)
address:
  - line: Box GW
  - line: 80 Waterman St
  - line: Brown University
  - line: Providence, RI 02906

# Build settings
markdown: kramdown
permalink: pretty