url: https://y7kim.github.io
baseurl: ''

# Site settings
title: The Edwards Lab
email: erika_edwards@brown.edu
description: "Erika Edwards's laboratory in the Department of Ecology and Evolutionary Biology at Brown University."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Erika Edwards
  pic: e_s
  position: Principal Investigator
  description: My CV is available <a href="/reprints/edwardsCV_2016.pdf">here</a>.
  social:
    - title: twitter
      url: https://twitter.com/erikaedw
    - title: google
      url: https://scholar.google.com/citations?user=mlC_ztAAAAAJ&hl=en&authuser=1
    - title: github
      url: https://github.com/erikajedwards
   
- name: Zachary Lewis
  pic: lewis
  position: Postdoc
  description: evolutionary morphology and development; organogenesis
  social:
   
- name: Eric Goolsby
  pic: goolsby
  position: Postdoc
  description: phylogenetic comparative methods, phylogenomics, plant ecophysiology
  social:
    - title: twitter
      url: https://twitter.com/evolgoolsby
    - title: google
      url: https://scholar.google.com/citations?user=bbEJDSQAAAAJ
    - title: github
      url: https://github.com/ericgoolsby
   
- name: Laura Garrison
  pic: LMG
  position: Graduate Student
  description: phenology, climate change, Viburnum, plant diversity and taxonomy.
  social:
   
- name: Lilly Hancock
  pic: lilly_s
  position: Graduate Student
  description: evolution of CAM photosynthesis; Australian Montiaceae. My CV is available <a href="reprints/HancockCVAug2012.pdf">here</a>
  social:
   - title: twitter
     url: https://twitter.com/lillypine28
   
- name: Morgan Moeglein
  pic: Morgan1
  position: Graduate Student
  description: Genetic basis of ecologically relevant traits; leaf shape evolution in Viburnum. <a href="reprints/Moeglein_CV_2014.pdf">CV</a>
   
- name: Elissa Johnson
  pic: Elissa_square
  position: Post-bac research associate
  description: Morphology, diversity, evolution, and natural history of all living things. I enjoy histology, imaging, and scientific illustration.
  social:
  url: elissajohnson.com
   
- name: Haley Carter
  pic: haley
  position: Undergrad
  description: phylogenetics, Viburnum, plant chemistry
   
- name: Lucy
  pic: lucy_moss
  position: Research Assistant
  description: botanical illustration; mosses 
   
- name: Henry
  pic: henry1_s
  position: Research Assistant
  description: flora of Mt. Kinabalu; bananas 
 





# Postal address (add as many lines as necessary)
address:
  - line: Box GW
  - line: 80 Waterman St
  - line: Brown University
  - line: Providence, RI 02906

# Build settings
markdown: kramdown
permalink: pretty