url: https://y7kim.github.io
baseurl: ''

# Site settings
title: The Edwards Lab
email: erika.edwards@yale.edu
description: "Erika Edwards's laboratory in the Department of Ecology and Evolutionary Biology at Yale University."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Erika Edwards
  pic: e_s
  position: Principal Investigator
  description: My CV is available <a href="/reprints/edwardsCVmay2018.pdf">here</a>.
  social:
    - title: twitter
      url: https://twitter.com/erikaedw
    - title: google
      url: https://scholar.google.com/citations?user=mlC_ztAAAAAJ&hl=en&authuser=1
    - title: github
      url: https://github.com/ejedwards
   
- name: Karolina Heyduk
  pic: karolina
  position: Donnelley Postdoc Fellow
  description: evolutionary physiology and genomics of CAM
  social:
    - title: twitter
      url: https://twitter.com/kheyduk
    - title: google
      url: https://scholar.google.com/citations?user=z3n2hIsAAAAJ&hl=en
   
- name: Jose Moreno-Villena
  pic: jose
  position: Postdoc
  description: phylogenetic comparative methods, phylogenomics, plant ecophysiology
  social:
    - title: google
      url: https://scholar.google.com/citations?user=EpuJnewAAAAJ&hl=en
    
   
- name: Morgan Moeglein
  pic: Morgan1
  position: Graduate Student
  description: Genetic basis of ecologically relevant traits; leaf shape evolution in Viburnum. 
  social:
   
- name: Ian Gilman
  pic: ian
  position: Graduate Student
  description: evolution of CAM photosynthesis; comparative phylogenetics, Portullugo.
  social:
   
- name: Anri Chomentowska
  pic: anri
  position: Graduate Student
  description: phylogenetics; evolutionary history of reproductive strategies; adaptation
  social:

- name: Joel Abraham
  pic: joel
  position: Post-bac research associate
  description: 
  social:

- name: Lucy
  pic: lucy_moss
  position: Research Assistant
  description: botanical illustration; mosses 
  social:

- name: Henry
  pic: henry1_s
  position: Research Assistant
  description: flora of Mt. Kinabalu; bananas 
  social:






# Postal address (add as many lines as necessary)
address:
  - line: PO Box 208105
  - line: 165 Prospect St
  - line: Yale University
  - line: New Haven, CT 06520

# Build settings
markdown: kramdown
permalink: pretty