url: https://ejedwards.github.io
baseurl: ''

# Site settings
title: The Edwards Lab
email: erika.edwards@yale.edu
description: "Erika Edwards's laboratory in the Department of Ecology and Evolutionary Biology at Yale University."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Erika Edwards (she/her)
  pic: e_s
  position: Principal Investigator
  description: My CV is available <a href="/reprints/edwardsCVaug2020.pdf">here</a>.
  social:
    - title: twitter
      url: https://twitter.com/erikaedw
    - title: google
      url: https://scholar.google.com/citations?user=mlC_ztAAAAAJ&hl=en&authuser=1
    - title: github
      url: https://github.com/ejedwards
   
   
- name: Jose Moreno-Villena
  pic: jose
  position: Postdoc
  description: phylogenetic comparative methods; phylogenomics; plant ecophysiology
  social:
    - title: google
      url: https://scholar.google.com/citations?user=TmTdiZQAAAAJ&hl=en

- name: Haoran Zhou
  pic: haoran
  position: NOAA Climate and Global Change Postdoc Fellow
  description: evolution of C3,C4,CAM photosynthesis; physiological and anatomical modeling
  social:
    - title: google
      url: https://scholar.google.com/citations?hl=en&authuser=1&user=6ch-jEIAAAAJ
    
- name: Shawn Abrahams (they/them)
  pic: shawn
  position: NSF Plant Genome Postdoc Fellow
  description: genomic comparison, phylogenomics, metabolic trait evolution, and systems biology
  social:
    - title: twitter
      url: https://twitter.com/Young_Eukaryote

- name: Ian Gilman
  pic: ian
  position: Graduate Student
  description: evolution of CAM photosynthesis; comparative phylogenetics; Portullugo.
  social:
    - title: github
      url: https://github.com/isgilman
   
- name: Anri Chomentowska
  pic: anri
  position: Graduate Student
  description: Montiaceae systematics; evolution of reproductive and life history strategies
  social:
    - title: twitter
      url: https://twitter.com/AChomentowska

- name: Josh Randall
  pic: josh
  position: Graduate Student
  description: ecophysiology; evolution of plant tissues and traits; urban adaptation
  social:

- name: Oluwatobi Oso
  pic: oluawatobi
  position: Graduate Student
  description: Plant anatomy, evolution and development; digital morphometrics and systematics
  social:
    - title: twitter
      url: https://twitter.com/OSO_Tee
    - title: google
      url:  https://scholar.google.com/citations?hl=en&user=b3Ct6aAAAAAJ


- name: Kirstin Dion
  pic: kirstin
  position: 
    Lab manager 
  description: and research associate
  social:

- name: Nora Heaphy
  pic: nora
  position: post-bac research associate
  description: climate niche evolution; species distribution models; Portullugo
  social:
    - title: twitter
      url: https://twitter.com/noraceae
    - title: github
      url: https://github.com/noraheaphy


- name: Lucy
  pic: lucy_moss
  position: Research Assistant
  description: botanical illustration; mosses 
  social:

- name: Henry
  pic: henry1_s
  position: Research Assistant
  description: flora of Mt. Kinabalu; bananas 
  social:




# Postal address (add as many lines as necessary)
address:
  - line: PO Box 208105
  - line: 165 Prospect St
  - line: Yale University
  - line: New Haven, CT 06520

# Build settings
markdown: kramdown
permalink: pretty